CXX=g++
CXXFLAGS=-g -Wall -pedantic -std=c++0x


balanced_paranthesis: balanced_paranthesis.o
	$(CXX) -o balanced_paranthesis balanced_paranthesis.o

.PHONY: clean

clean:
	rm -f ./*.o ./balanced_paranthesis
